
name: Writing GitHub Metrics to Googlesheet
on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  write-data:
    name: Write Data
    runs-on: ubuntu-latest
    container:
      image: cansav09/metricminer

    steps:
      - name: Get GitHub Data
        env:
          METRICMINER_GITHUB_PAT: ${{ secrets.METRICMINER_GITHUB_PAT }}
        run: |
          library(magrittr)

          # Authorize GitHub
          metricminer::auth_from_secret("github", token = Sys.getenv("METRICMINER_GITHUB_PAT"))

          gsheet <- "https://docs.google.com/spreadsheets/d/1lk3vMgE4CNuACrI1mzHrv6AsvXbdhw1zJENMkIEhrZs/edit#gid=0"
          repos <- c(
              "fhdsl/metricminer",
              "fhdsl/metricminer.org",
              "jhudsl/ottrpal",
              "jhudsl/ari",
              "jhudsl/cow",
              "jhudsl/ottrproject.org",
              "jhudsl/ottr_docker",
              "jhudsl/ottr-reports",
              "fhdsl/conrad",
              "jhudsl/text2speech",
              "jhudsl/OTTR_Quizzes",
              "jhudsl/OTTR_Template",
              "jhudsl/OTTR_Template_Website",
              "jhudsl/ITCR_Tables",
              "jhudsl/ITN_Platforms",
              "fhdsl/Choosing_Genomics_Tools",
              "jhudsl/Informatics_Research_Leadership",
              "jhudsl/Documentation_and_Usability",
              "jhudsl/Reproducibility_in_Cancer_Informatics",
              "jhudsl/Adv_Reproducibility_in_Cancer_Informatics",
              "fhdsl/GitHub_Automation_for_Scientists",
              "jhudsl/Computing_for_Cancer_Informatics",
              "fhdsl/Overleaf_and_LaTeX_for_Scientific_Articles",
              "fhdsl/Ethical_Data_Handling_for_Cancer_Research",
              "fhdsl/AI_for_Decision_Makers",
              "fhdsl/AI_for_Efficient_Programming",
              "fhdsl/NIH_Data_Sharing"
          )
          repo_metrics <- metricminer::get_multiple_repos_metrics(repo_names = repos, time_course = TRUE)

          combine_data <- googlesheets4::read_sheet(gsheet) %>%
            dplyr::bind_rows(repo_metrics) %>%
              dplyr::distinct()

          datasheet <- metricminer::write_to_gsheet(gsheet = gsheet,
            input = combine_data,
            overwrite = TRUE)

        shell: Rscript {0}

      - name: Get Google Analytics
        env:
          METRICMINER_GOOGLE_ACCESS: ${{ secrets.METRICMINER_GOOGLE_ACCESS }}
          METRICMINER_GOOGLE_REFRESH: ${{ secrets.METRICMINER_GOOGLE_REFRESH }}
        run: |
          library(magrittr)

          # Authorize Google
          metricminer::auth_from_secret("google",
                 refresh_token = Sys.getenv("METRICMINER_GOOGLE_REFRESH"),
                 access_token = Sys.getenv("METRICMINER_GOOGLE_ACCESS"),
                 cache = TRUE
          )
          gsheet <- "https://docs.google.com/spreadsheets/d/1lk3vMgE4CNuACrI1mzHrv6AsvXbdhw1zJENMkIEhrZs/edit#gid=0"

          property_ids <- c(
            "AI for Efficient Programming" = "394586786",
            "NIH Data Sharing" = "394728918",
            "AI for Decision Makers" = "419135893",
            "ITN Website" = "289307553",
            "Leadership in Cancer Informatics" = "289320404",
            "Documentation and Usability" = "289316473",
            "Computing for Cancer Informatics" = "291756783",
            "Reproducibility in Cancer Informatics" = "292114138",
            "Advanced Reproducibility in Cancer Informatics" = "295510538",
            "Ethical Data Handling" = "317734322",
            "OTTR website" = "356029144",
            "Choosing Genomics Tools" = "394589059",
            "Overleaf and Latex for Scientific Articles" = "398085657",
            "GitHub Automation for Scientists" = "413056614",
            "metricminer.org" = "423445968")

          ga_metrics <- lapply(property_ids, get_ga_stats)

          names(ga_metrics) <- names(property_ids)

          metrics_df <- ga_metrics %>%
            dplyr::bind_rows(.id = "website")

          datasheet <- metricminer::write_to_gsheet(gsheet = gsheet,
            input = metrics_df,
            sheet = "google_analytics_metrics",
            overwrite = TRUE)

        shell: Rscript {0}
